### ISSUE TITLE
Add a link to the form Aiden sent me

### ISSUE THREAD

**Issue by abejfehr** [abejfehr/CSSS#14]
Right hurr: [https://docs.google.com/forms/d/1lHlYt_kVFW131gPEa8_xtAtTGtoFergrSx-qJlo66wc/viewform?c=0&w=1](https://docs.google.com/forms/d/1lHlYt_kVFW131gPEa8_xtAtTGtoFergrSx-qJlo66wc/viewform?c=0&w=1)

**Comment by abejfehr** [comment]
This can be one of the orange buttons

**Comment by abejfehr** [comment]
Is this form still functional? I was going to add it to the front page now but it looks like it's closed.

**Comment by CarletonSSS** [comment]
This link should now be available for use

-Aiden

**Comment by CarletonSSS** [comment]
https://docs.google.com/forms/d/1XoQL40XxERODSEHSlAzFHHCfBtWo9sIW1uV6atmyKmE

Hi Abe, above should be the link that you can post volunteering with the society. It would be awesome if you can get this up before the beginning of August. Thanks for all your help with everything!

-Garrett

**Comment by abejfehr** [comment]
@CarletonSSS I made it so when you click "GET INVOLVED" it takes you to the form. Is that acceptable?

**Comment by CarletonSSS** [comment]
http://prntscr.com/7l0r3s

http://needsmorejpeg.com/img/fb-img.1427991554.jpg

lmao

On Wed, Jun 24, 2015 at 10:42 PM, Abe Fehr notifications@github.com wrote:

> @CarletonSSS https://github.com/CarletonSSS I made it so when you click
> "GET INVOLVED" it takes you to the form. Is that acceptable?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/14#issuecomment-115078538.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by CarletonSSS** [comment]
wrong issue... too many emails to handle

On Wed, Jun 24, 2015 at 10:45 PM, Sebastian Srugo <
operations@sciencesociety.ca> wrote:

> http://prntscr.com/7l0r3s
> 
> http://needsmorejpeg.com/img/fb-img.1427991554.jpg
> 
> lmao
> 
> On Wed, Jun 24, 2015 at 10:42 PM, Abe Fehr notifications@github.com
> wrote:
> 
> > @CarletonSSS https://github.com/CarletonSSS I made it so when you
> > click "GET INVOLVED" it takes you to the form. Is that acceptable?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/abejfehr/CSSS/issues/14#issuecomment-115078538.
> 
> ## 
> 
> http://www.sciencesociety.ca/
> _Sebastian Srugo_
> Vice President Operations
> Carleton Science Student Society
> 3412 Herzberg Laboratories
> 1125 Colonel By Drive
> Ontario, K1S 5B7
> www.sciencesociety.ca
> https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
> https://twitter.com/carletonsss] https://twitter.com/carletonsss

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
I'm just going to assume this is alright. If not, re-open this or make a new issue :palm_tree:
