### ISSUE TITLE
Make orange buttons just buttons

### ISSUE THREAD

**Issue by abejfehr** [abejfehr/CSSS#15]
Instead of turnaround thingies

**Comment by CarletonSSS** [comment]
did u forget about this or is it just hard so ur leaving it till later? lmao

**Comment by abejfehr** [comment]
Yeah....I'm putting it off because it's not that easy. I'll do it, I swear!

**Comment by abejfehr** [comment]
I hope this is an acceptable look. I'll close this for now, but it can be re-opened if you have further suggestions about these links
