### ISSUE TITLE
Change fonts to helvetica (if it looks better than before)

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#16]

**Comment by CarletonSSS** [comment]
Please have this done by the end of the month (June).

--Aiden

**Comment by abejfehr** [comment]
I tried the fonts both ways(on the clubs page actually) and here are the results.

Helvetica:
![helvetica](https://cloud.githubusercontent.com/assets/3917428/8447689/5766a9b2-1f8a-11e5-9915-550b5b66f9c8.png)

Current fonts:
![other](https://cloud.githubusercontent.com/assets/3917428/8447691/691c6ca0-1f8a-11e5-8910-c82308786bd5.png)

I'm definitely a fan of the current fonts vs straight Helvetica. The text that's in the club boxes looks very plain the way that it is now. The current slab serif gives it a bit more style.

Let me know what you think!

**Comment by CarletonSSS** [comment]
Keep the current font, youre right it looks better

On Wednesday, July 1, 2015, Abe Fehr notifications@github.com wrote:

> I tried the fonts both ways(on the clubs page actually) and here are the
> results.
> 
> Helvetica:
> [image: helvetica]
> https://cloud.githubusercontent.com/assets/3917428/8447689/5766a9b2-1f8a-11e5-9915-550b5b66f9c8.png
> 
> Current fonts:
> [image: other]
> https://cloud.githubusercontent.com/assets/3917428/8447691/691c6ca0-1f8a-11e5-8910-c82308786bd5.png
> 
> I'm definitely a fan of the current fonts vs straight Helvetica. The text
> that's in the club boxes looks very plain the way that it is now. The
> current slab serif gives it a bit more style.
> 
> Let me know what you think!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/16#issuecomment-117433078.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss
