### ISSUE TITLE
Remove curse words

### ISSUE THREAD

**Issue by abejfehr** [abejfehr/CSSS#21]
There are at least 3 occurrences in the code of the word "shit":
https://github.com/abejfehr/CSSS/search?utf8=%E2%9C%93&q=shit

Come on, this is a public-facing page that represents the school.

**Comment by CarletonSSS** [comment]
This needs to be done by June 13th 2015 please. Most likely the biggest issue. The removal of any passage containing the swears may simply be removed.

--Aiden

**Comment by abejfehr** [comment]
I actually already fixed this, I just hadn't merged it yet. Did it today, there shouldn't be any curse words now \o/
