### ISSUE TITLE
For Science Cafe info under Events

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#28]
anyway we can make the part that says "Sunnyside branch of the Ottawa Library" a google maps link to where that is?

**Comment by abejfehr** [comment]
That's a good idea and it should be very doable. I'll try it out later today or next week

**Comment by CarletonSSS** [comment]
all of these are whenever you have time! just writing down what im seeing
should be fixed now since im on the website

On Fri, Jun 12, 2015 at 1:18 PM, Abe Fehr notifications@github.com wrote:

> That's a good idea and it should be very doable. I'll try it out later
> today or next week
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/28#issuecomment-111563336.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
@CarletonSSS let me know what you think of the map I added. I can change it if it needs to be different

**Comment by CarletonSSS** [comment]
Looks good!

On Saturday, June 13, 2015, Abe Fehr notifications@github.com wrote:

> @CarletonSSS https://github.com/CarletonSSS let me know what you think
> of the map I added. I can change it if it needs to be different
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/28#issuecomment-111757901.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss
