### ISSUE TITLE
Not really an issue..

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#30]
Here is the link to the ottawa u equivalent of the CSSS: http://www.ssaaes.com

If you see anything that we dont have that you like, you can try to implement it into our website!

**Comment by abejfehr** [comment]
The twitter box in the bottom right corner of [this](http://www.ssaaes.com/our-services/) page drives me nuts, it looks like it's perma-highlighted.

I'll see if I can get some inspiration from their page though

**Comment by abejfehr** [comment]
I'm gonna go ahead and close this one
