### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#36]
Sometimes the drop down menu is in this font (which is the one i like the best)
http://prntscr.com/7h2sfs

And sometimes depending on what page you are on it changes to this
http://prntscr.com/7h2sss

which i am guessing is bolded since i am on the councillors page, but i think it would be better if it turned red like the rest of the menu fonts when you go to their respective sites. :+1:

**Comment by abejfehr** [comment]
Yup, this is because you're on the councillors page. It should be a quick fix

**Comment by abejfehr** [comment]
Fix'd
