### ISSUE TITLE
Menu pictures

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#37]
Not a fan of the skyline behind the logo or the background on the other one
what if we tried the solid red colour that we have on the logo but with a somewhat opaque white on top to make it easier to read on?

**Comment by abejfehr** [comment]
I think a nice picture of the Carleton campus with Dunton Tower and everything would look good there. What do you think?

**Comment by abejfehr** [comment]
Like this one: http://ww1.prweb.com/prfiles/2010/09/28/49608/CarletonUniversity.jpg

**Comment by CarletonSSS** [comment]
Try it  and ill check it out!

On Monday, June 15, 2015, Abe Fehr notifications@github.com wrote:

> Like this one:
> http://ww1.prweb.com/prfiles/2010/09/28/49608/CarletonUniversity.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/37#issuecomment-112149202.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
@CarletonSSS Let me know what you think of the images. I tried a scenic picture of Carleton and tunnel art. Not sure if I'm a fan of the second one, and I would've definitely rather used [this image](https://www.campusvibez.ca/wp-content/uploads/carleton3.jpg) or [this one](http://carleton.ca/hr/wp-content/uploads/carleton-university-with-otrain.jpg) if it was better quality

**Comment by CarletonSSS** [comment]
check out my other comment that had to do with this issue.. Also lets take
out the "CSSS", we decided that there was no need for that haha

**Comment by abejfehr** [comment]
I'll remove CSSS next time I make a change, so I'll leave this open. Also I never noticed that pixelation on my screen lol, I did compress that image twice though and that's probably why it's so bad. I'll re-do it when I get the chance!
