### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#39]
How about instead of the two pictures on the events page, we place a calendar there that shows when our events are and then people can add them to their calendar by clicking on the events?

**Comment by abejfehr** [comment]
This is pretty difficult actually, and it probably doesn't seem like it. I'll definitely look into it though.

I thought this comic would be appropriate to describe how this is:

![XKCD - Tasks](http://imgs.xkcd.com/comics/tasks.png)

**Comment by CarletonSSS** [comment]
How about something like the events "calendar" (more like a list of events and their dates) that you can add to your calendar like the ottawa u science society page:

http://www.ssaaes.com

**Comment by abejfehr** [comment]
So regarding this: 

The SSAAESSSS(hardest acronym ever) uses something called [Tribe Calendar](https://theeventscalendar.com/product/wordpress-events-calendar/) in their website, and it's a plugin for Wordpress. Unfortunately we're not using Wordpress but we can probably find an alternative to generate calendars.

#### Alternatives
- If we keep a plain list of events, we can use [AddThisEvent](https://addthisevent.com/) to let people add it to their calendars in a very beautiful way
- [Tockify](https://tockify.com/) - not my favorite
- [UpTo](https://upto.com/embed-calendar) - **My favorite**. Isn't it so nice? Dunno if it strikes your fancy, but this is _probably_ what I'd choose
- [LoCalendar](https://www.localendar.com/elsie) - doesn't seem very pretty, but it looks like it gets the job done
- [30Boxes](http://30boxes.com/welcome.php) - looks like garbage to me, not even sure why I put it in the list
- Embedding [Google Calendars](https://support.google.com/calendar/answer/41207?hl=en) - a good quick n' dirty solution

Let me know which one you think we should use and I can add a calendar/event list to the page sometime

**Comment by CarletonSSS** [comment]
Seems like you like UpTo, so im going to go with your choice ahah

On Mon, Jul 13, 2015 at 11:38 PM, Abe Fehr notifications@github.com wrote:

> So regarding this:
> 
> The SSAAESSSS(hardest acronym ever) uses something called Tribe Calendar
> https://theeventscalendar.com/product/wordpress-events-calendar/ in
> their website, and it's a plugin for Wordpress. Unfortunately we're not
> using Wordpress but we can probably find an alternative to generate
> calendars.
> Alternatives
> - If we keep a plain list of events, we can use AddThisEvent
>   https://addthisevent.com/ to let people add it to their calendars in
>   a very beautiful way
> - Tockify https://tockify.com/ - not my favorite
> - UpTo https://upto.com/embed-calendar - _My favorite_. Isn't it so
>   nice? Dunno if it strikes your fancy, but this is _probably_ what I'd
>   choose
> - LoCalendar https://www.localendar.com/elsie - doesn't seem very
>   pretty, but it looks like it gets the job done
> - 30Boxes http://30boxes.com/welcome.php - looks like garbage to me,
>   not even sure why I put it in the list
> - Embedding Google Calendars
>   https://support.google.com/calendar/answer/41207?hl=en - a good
>   quick n' dirty solution
> 
> Let me know which one you think we should use and I can add a
> calendar/event list to the page sometime
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/39#issuecomment-121124919.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
The calendar is up and sort of pretty now(at least I think it is). Let me know what you think about how it looks. You'll need to notify me when there's events to add, unless whoever is in charge of events wants to make an UpTo account and add the events themselves(it's easy)

**Comment by abejfehr** [comment]
I'm gonna go ahead and close this since the calendar is up. Y'all can email me if you need an event in there
