### ISSUE TITLE
Councillors link has terrible quality pictures

### ISSUE THREAD

**Issue by abejfehr** [abejfehr/CSSS#4]
Need to improve the quality, change the people's roles, remove the chair, etc.

**Comment by CarletonSSS** [comment]
For now please look into why there is only one good picture and how we can ensure that next time all of them will be. Please report back at the end of the month (June) since this is not a pressing issue.

--Aiden

**Comment by abejfehr** [comment]
It looks like the pictures for the people on that page were just pulled from the thumbnails(not even the full size) of their Facebook profile pictures. Can I get a list of all the people that are in the CSSS as well as an optional bio and a picture?

**Comment by CarletonSSS** [comment]
I sent u an email during the last meeting with all the winners of the positions. We will probably be taking exec pictures later so they are cohesive, and then emailing the reps to get their pictures later + bios. For now can u find a picture like the one martin put for people who dont have a picture (but better) and just only use that picture and input everyones names at least. Later we will have bios and actual pictures to implement.

Sebastian

**Comment by abejfehr** [comment]
I see that's the email with the 2 PDF's, and I'm assuming I'm only taking the names of the representatives in purple. Is there any reason my department/name isn't on any of those pages? Doesn't that mean there could be other people missing?

**Comment by CarletonSSS** [comment]
Thats really weird...Ill check with John later but for now we can just put
up the names that we have

On Fri, Jun 12, 2015 at 1:03 PM, Abe Fehr notifications@github.com wrote:

> I see that's the email with the 2 PDF's, and I'm assuming I'm only taking
> the names of the representatives in purple. Is there any reason my
> department/name isn't on any of those pages? Doesn't that mean there could
> be other people missing?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/4#issuecomment-111558402.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by CarletonSSS** [comment]
check the elections page that was on the website before to find out who
ran. the people who ran unopposed would have gotten a seat without having
to have a vote

On Fri, Jun 12, 2015 at 1:07 PM, Sebastian Srugo <
operations@sciencesociety.ca> wrote:

> Thats really weird...Ill check with John later but for now we can just put
> up the names that we have
> 
> On Fri, Jun 12, 2015 at 1:03 PM, Abe Fehr notifications@github.com
> wrote:
> 
> > I see that's the email with the 2 PDF's, and I'm assuming I'm only taking
> > the names of the representatives in purple. Is there any reason my
> > department/name isn't on any of those pages? Doesn't that mean there could
> > be other people missing?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/abejfehr/CSSS/issues/4#issuecomment-111558402.
> 
> ## 
> 
> http://www.sciencesociety.ca/
> _Sebastian Srugo_
> Vice President Operations
> Carleton Science Student Society
> 3412 Herzberg Laboratories
> 1125 Colonel By Drive
> Ontario, K1S 5B7
> www.sciencesociety.ca
> https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
> https://twitter.com/carletonsss] https://twitter.com/carletonsss

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
I guess that accounts for me and probably anyone else that would be missing. I'll take a look at that, and I'll have it updated as soon as I possibly can. Thanks!

**Comment by abejfehr** [comment]
@CarletonSSS I updated the councillors on the page and added a new placeholder picture for people that don't currently have one. If either one of you guys(Seb or Aiden) could send an email blast asking for a decently large picture and a bio, as well as optionally a facebook or twitter, that would be awesome!

I'm missing a few people I believe, as there used to be a "directors" section but I didn't see directors in the PDFs you sent. I'm also not sure the Elections page on the old site was comprehensive, because I didn't have an entry on there either.

Anyways, let me know how I can make it better and I'll do everything I can.
