### ISSUE TITLE
Councillors

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#40]
For the five execs at the top of council page, could you center the last two executives instead of having them to the right?

**Comment by abejfehr** [comment]
That sounds difficult, only because the site is built with bootstrap which uses a [grid system](http://getbootstrap.com/css/#grid), and the list of councillors is dynamically produced(it's not hard-coded).

I think there's workarounds online, so I'll try those and see what I can do.

**Comment by abejfehr** [comment]
This is now done!
