### ISSUE TITLE
Recent News in the footer

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#41]
Delete Recent News from the footer, bring links to the center and at the far right add the location of the science society: 3412 Herzberg, with the address of carleton university, and make it so that by pressing on this, google maps opens and shows you where we are located.

Also, to replace recent news I was thinking of having a news bar at the top like on the news on tv that rolls over and shows new info. Maybe make it red like the csss logo

thanks again

sebastian

**Comment by abejfehr** [comment]
For the "news bar at the top" do you mean a [marquee](https://en.wikipedia.org/wiki/Marquee_element)? If so, that tag is deprecated now but there are a million alternatives I can use to make it

**Comment by CarletonSSS** [comment]
yeah a marquee. at first i was thinking that each piece of news would come
up as a sentence  all at once and then the next sentence would appear while
the last disappeared.

I just think its harder to read when the whole sentence is moving one way
or the other. Try it out tho

On Wed, Jul 1, 2015 at 1:00 AM, Abe Fehr notifications@github.com wrote:

> For the "news bar at the top" do you mean a marquee
> https://en.wikipedia.org/wiki/Marquee_element? If so, that tag is
> deprecated now but there are a million alternatives I can use to make it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/41#issuecomment-117434051.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
I think that gray bar at the top has enough space in the middle that you could put news headlines in there and link them to "articles". Blog updates from RXN maybe? (I have no idea what kind of content you intend on putting there, I'm only guessing)

**Comment by CarletonSSS** [comment]
At the footer of the to the right of "Where to find us"

Please put our office hours for the semester

Mon:  
12:00 pm-1:00 pm
Tue:  
1:00 pm-2:00 pm
Wed:  
10:00 am-11:00 am
Thu:  
12:00 pm-1:00 pm
Fri:  
10:30 am-11:30 am

Thank you

-Aiden

**Comment by abejfehr** [comment]
My bad Aiden, I didn't see your update until now. Gotta get myself together...

Closing now
