### ISSUE TITLE
Add club info

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#45]
Carleton Chemistry and Biochemistry Society

Logo: https://www.mediafire.com/?5yg75pvwp3a83nq
Contact: ccbs.carleton@gmail.com
Website: https://www.facebook.com/CCBS.Carleton

Format:

Title
Logo
Contact
Website

Please have this done by the end of the month

--Aiden

**Comment by abejfehr** [comment]
I'll be working on this late tonight or tomorrow morning! Hopefully this and a couple of other issues should be taken care of.
