### ISSUE TITLE
the orange buttons

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#48]
http://prntscr.com/7nk8dt

cant you just make the little circular icons into links?

**Comment by abejfehr** [comment]
Oh, I just realized that they're displaying funny now.

Yeah, but I want the text to be somewhere so the user knows what they're clicking on, an icon isn't enough. I'd still like the orange button underneath for a label or something.

**Comment by CarletonSSS** [comment]
it can still say like meetings or events under, and when u scroll onto the icon itll change a shade darker and when u click it goes to the respective part of the website.. thats what i was thinking at least
