### ISSUE TITLE
This is badly written

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#51]
Look at the subheading under Events. It reads..

"Carleton Science Student Society has a historic role of hosting events that promote both an opportunity for our students to expand both their academic insights while meeting like-minded individuals."

**Comment by abejfehr** [comment]
Yeah, "both" :stuck_out_tongue: 

Do you have any suggestions?

**Comment by CarletonSSS** [comment]
"Carleton Science Student Society has a historic role of hosting events that promote both an opportunity for our students to expand their academic insights, while meeting like-minded individuals."
