### ISSUE TITLE
NEW PAGE

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#52]
We're going to be starting a blog on the CSSS website, and I want to make a new page for it on the website: http://prntscr.com/7pllu5 like so lol

We have a font type for the blog (which i will send to ur webmaster email) that I want you to use where I typed "The RXN" on that pic.

Once you look at the logo you may notice that the "the" part is small and might not be seen for the button I want you to create, so I would consider take that "the", making it a bigger font size and just placing it above "RXN" instead of in the R of the word.

For the page itself, if you could design a sexy "under construction" or "coming soon" or something like that for the page that would be great for now.

Not sure how long it takes to code a new page so you tell me what your deadline would be haha
- Seb

**Comment by abejfehr** [comment]
I'll see if I can have this done in a few weeks. I'm gonna work on some other issues today though. The CSSS site is a one-night-a-week thing for me right now, I hope that's alright

**Comment by abejfehr** [comment]
Also I don't have the password for the webmaster email, so if someone did send me a message I would've never received it :tongue: Could you send me the information I need to log into that, perhaps to my gmail? Thanks!

**Comment by CarletonSSS** [comment]
ill fb message you the password now lol
Also I was wondering how much flexibility there will be for the new page in terms of design. I want it to be drastically different from the other pages because its going to be more of a blog / news hub so I want it to look more like that. Can you tell me what you can and cant do? If i give you a sketch of a design could you do that or are there some things that arent possible with this type of website?

**Comment by abejfehr** [comment]
Make a sketch/design of what you want first and send me an email or something, then I can critisize it in detail. This will likely be quite a bit of work, so you'll have to be a bit patient with me on the RXN page

**Comment by CarletonSSS** [comment]
Sent u a design to ur webmaster email just now

**Comment by abejfehr** [comment]
I have the RXN button finalized now, I just need a place to link it to. Obviously you purchased your domain, but there's no way that it knows to point to github just yet. You'll need to tell your domain registrar(godaddy or something) where to point, because right now they don't know where to send a user. I can help you out with this if you need assistance, maybe we can meet up before/after the next CUSA meeting or something. Besides that, you could look at the way that I configured GoDaddy for sciencesociety.ca for inspiration. The configuration _should_ be the same

**Comment by CarletonSSS** [comment]
*GO Daddy Account*
Account No. 47276251
Password: ScienceSociety1!

On Sunday, August 2, 2015, Abe Fehr <notifications@github.com> wrote:

> I have the RXN button finalized now, I just need a place to link it to.
> Obviously you purchased your domain, but there's no way that it knows to
> point to github just yet. You'll need to tell your domain registrar(godaddy
> or something) where to point, because right now they don't know where to
> send a user. I can help you out with this if you need assistance, maybe we
> can meet up before/after the next CUSA meeting or something. Besides that,
> you could look at the way that I configured GoDaddy for sciencesociety.ca
> for inspiration. The configuration *should* be the same
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abejfehr/CSSS/issues/52#issuecomment-127051102>.
>


-- 

<http://www.sciencesociety.ca/>
*Sebastian Srugo*
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
<https://www.facebook.com/CarletonScienceStudentSociety?fref=ts>   [image:
https://twitter.com/carletonsss] <https://twitter.com/carletonsss>

**Comment by abejfehr** [comment]
Closing this issue. Issues related to therxn.ca can be created in that repo, to which I believe I made you contributor also(let me know if you're not)
