### ISSUE TITLE
Referendum

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#56]
we may have a referendum for a levy during early october so i want to have a lot of media presence at that time. Since I have time now, I wanted to take the time to make a front page picture for that time. Just wanted to know what the resolution and size of the pictures u display on the front page are so I can make one for that time.

please answer to this email asap so I can start

thanks
Seb

**Comment by abejfehr** [comment]
You can approximate, that's what I've been doing. The picture just takes up as much space as it can so long as it fills the area. For a reference, you could use http://www.sciencesociety.ca/images/slideshow1.jpg since that shows pretty nicely

**Comment by abejfehr** [comment]
I'm going to close this since it's not really a current issue. If you need something done with the referendum, you can create a new Github issue at that time
