### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#61]
Tomorrow we will be putting up the application form for the director positions of the science society. I am now sending you a photoshop file with a coverphoto I want you to add to the gallery at the starting page. If you could please have this coverphoto up tomorrow morning or late tonight and have a button that says  click here for more info that would be great.

The button should take them to a application sheet pdf that I will be sending you later tonight since its not on my computer right now. On this sheet at the top and at the bottom there are links to the application questionnaire (something like goo.gl...). If you could make these links so that they can directly click on these and go to the questionnaire that would be great!

Message me if any of this is confusing haha
Sebastian

**Comment by abejfehr** [comment]
I'll have to work on it late tonight, but I'll try to get some stuff done

**Comment by CarletonSSS** [comment]
sounds good, as long as its up by tomorrow early morning! Ill send u the application at about 8ish

**Comment by CarletonSSS** [comment]
when should i expect this to be up? Just so I know when to look to see it done

**Comment by abejfehr** [comment]
Just got home from dropping my girlfriend off at her place. Hopefully like <1hr from now? I'd say check back in 2 hours or so if you're up, just to be safe. I'll tag the commit in this issue when it's done though so you should be notified

**Comment by CarletonSSS** [comment]
sounds good! Could u also hide the "meetings" page for now? since well
probably be getting some traffic from the director applications, I dont
want anyone to see that page since its pretty bad lol

On Mon, Jul 13, 2015 at 10:10 PM, Abe Fehr notifications@github.com wrote:

> Just got home from dropping my girlfriend off at her place. Hopefully like
> <1hr from now? I'd say check back in 2 hours or so if you're up, just to be
> safe. I'll tag the commit in this issue when it's done though so you should
> be notified
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/61#issuecomment-121111401.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
Sure. My bad. I haven't gotten around to cleaning that up yet

**Comment by CarletonSSS** [comment]
isnt your fault that martin left it like that haha

On Mon, Jul 13, 2015 at 10:20 PM, Abe Fehr notifications@github.com wrote:

> Sure. My bad. I haven't gotten around to cleaning that up yet
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/61#issuecomment-121113484.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss
