### ISSUE TITLE
I have no idea about this stuff..

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#62]
For the blog I want to have it so that therxn.ca also connects to the blog, rather than having to go through our site. Can you find out how much it would cost to buy this domain cause it tells me I need to buy hosting too? Not sure if you know of any other domain buying sites

**Comment by abejfehr** [comment]
It would be 10 bucks, and we could host it on here as well, it would just be a completely separate site though. Check on [who.is](http://who.is/) to see if it's available and you can buy domains from [GoDaddy](https://www.godaddy.com/) or I usually get mine from [Dynadot](https://www.dynadot.com/)

**Comment by CarletonSSS** [comment]
question about purchasing domains. We bought sciencesociety.ca from godaddy and im looking at godaddy now to buy therxn.ca; it says the domain costs 10$ but then it gives me this http://prntscr.com/7t905h

So its forcing me to do these things and pay.. dont know if theres a way around that. So my question is, if we buy it from dynadot, since both of these are assets, can we get like a sheet of paper that says we own it / can we put them both on one website so that we can renew easily..

**Comment by abejfehr** [comment]
You can transfer the ownership and move them between registrars, but since you're already with GoDaddy I'd probably suggest to stick with them. They're just trying to put you in a corner with all those bells and whistles, but it should be possible to buy ONLY the domain from them without all that other crap

**Comment by CarletonSSS** [comment]
ok ill call them tomorrow and figure it out cause the website wont let me
not buy those things lol

On Thu, Jul 16, 2015 at 12:23 AM, Abe Fehr notifications@github.com wrote:

> You can transfer the ownership and move them between registrars, but since
> you're already with GoDaddy I'd probably suggest to stick with them.
> They're just trying to put you in a corner with all those bells and
> whistles, but it should be possible to buy ONLY the domain from them
> without all that other crap
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/62#issuecomment-121825480.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by CarletonSSS** [comment]
kk i just bought it for 10 a year for 2 years. Once you make a "coming soon" page for the rxn and the button on the sceince society website you can link it to the page

**Comment by abejfehr** [comment]
We're talking about therxn.ca stuff in 2 other issues now, so I'll close this one
