### ISSUE TITLE
Coming Soon

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#64]
Any chance you can create the The RXN button on the science society page and have it link to therxn.ca and have the page just be a coming soon thing that looks nice by this weekend?

**Comment by CarletonSSS** [comment]
ping

**Comment by abejfehr** [comment]
I have the link for this page made(on my computer) and right now I'm just working on getting it so it's positioned correctly on all different screen sizes. Should be a couple more days only, sorry bout the delays

**Comment by abejfehr** [comment]
Done! Lemme know what you think

**Comment by CarletonSSS** [comment]
dont like how the button isnt the logo; it should be the logo and it should
be beside the current csss logo at the top left. the underconstruction page
is fine since we have to actually have the page ready by september... Can
you have that by september lmao

On Wed, Aug 12, 2015 at 12:20 AM, Abe Fehr notifications@github.com wrote:

> Done! Lemme know what you think
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abejfehr/CSSS/issues/64#issuecomment-130155615.

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
My bad on using text instead of the logo, I will replace that ASAP. In regards to the positioning, I had understood that this was the intention: http://prntscr.com/7pllu5 which shows the logo at the top-right as it is now

**Comment by abejfehr** [comment]
It's the logo now, but I kept the placement

**Comment by CarletonSSS** [comment]
actually how about u make it like the other tabs and it can say: THE RXN,
under it it can say "Science News" and when u hover over it can say "Made
By & For You"

**Comment by CarletonSSS** [comment]
NVM leave it as is

On Wed, Aug 12, 2015 at 12:35 AM, Sebastian Srugo <
operations@sciencesociety.ca> wrote:

> actually how about u make it like the other tabs and it can say: THE RXN,
> under it it can say "Science News" and when u hover over it can say "Made
> By & For You"

## 

http://www.sciencesociety.ca/
_Sebastian Srugo_
Vice President Operations
Carleton Science Student Society
3412 Herzberg Laboratories
1125 Colonel By Drive
Ontario, K1S 5B7
www.sciencesociety.ca
https://www.facebook.com/CarletonScienceStudentSociety?fref=ts   [image:
https://twitter.com/carletonsss] https://twitter.com/carletonsss

**Comment by abejfehr** [comment]
Alright, it's up to you. I'm gonna close this, if you need any changes to the button in the future you can make a new issue
