### ISSUE TITLE
Make a contact page

### ISSUE THREAD

**Issue by abejfehr** [abejfehr/CSSS#7]
It would have the room number and the executives' email addresses(not the councillors).

**Comment by CarletonSSS** [comment]
Not really necessary as a new page, Id suggest putting our room number at the footer and the emails can be found on the council page! Im thinking we could get rid of the "welcome to csss" paragraph (who reads that anyway?) on the footer at the left and put in the carleton address where we are located. What do you think?

**Comment by CarletonSSS** [comment]
Oh nvm to not needing it, I didnt understand that you could send email from this page you are creating, thats cool. but everything else I said still applies (about the footer and the paragraph)

**Comment by abejfehr** [comment]
I put the Carleton address in the right side for #41, which takes care of your first comment. You're right about just using the councillors page to find people's email addresses.

I wanted to use [formspree](http://formspree.io/) to handle sending emails from a form on the contact page, but actually this is a bit more difficult than I had anticipated.

My vision was to have a dropdown where you could pick a councillor to email, a textbox for a subject and another big one for the message. This is all fine and dandy, but formspree requires that you activate your email in order to receive further emails. That means that for each councillor we'd have to send a dummy email just to activate the accounts, and I'm a little hesitant to put everyone through that.

Even if I were willing to subject everyone to that, next year's councillors would be new and have new emails, and the webmaster then(if it's not me) may not understand how formspree works and might not remember to activate their email addresses. In that case, you have missing communication, because the message that should've been delivered may have been important.

Dunno man, I'll see if I can find an alternative email service though

**Comment by CarletonSSS** [comment]
We can make generic "biologyrep1@sciencesociety.ca" for each position or we can make "FirstnameLastname@sciencesociety.ca" and change it every year through gmail.

I agree though that the lack of someone understanding the program could be problemsome if we want to change them. 

The other thing we could do is filter the emails through one of the execs so we guarantee a response and not need to change the email. 

I'll bring up the formating when I see everyone.

-Aiden
