### ISSUE TITLE
Jannelle Lamontagne photo/bio

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#87]
I'm Jannelle, I'm a 3rd year Neuroscience and Mental Health student, a mentor and First Year Representative co-coordinator with the SSSC and Vice President of the Carleton University Biology Society. In my free time I scroll aimlessly through mostly tumblr or play guitar&drums. 

![unnamed](https://cloud.githubusercontent.com/assets/12619101/11280347/a22f7c96-8ec3-11e5-8bec-a9d207eacc53.jpg)

**Comment by abejfehr** [comment]
Again, forgot to reference :tired_face: a927dd9020782342acaed8ad4e217f955f939bf0
