### ISSUE TITLE
Remove the Winter Formal

### ISSUE THREAD

**Issue by abejfehr** [abejfehr/CSSS#9]
Put some kind of message to calm down impatient science-lovers

**Comment by CarletonSSS** [comment]
"Annual Science Winter Formal!!!

Your Vice President Programming and their committee is hard at work to give you the best Science Winter Formal each year! 

When? February of each year -- Stay tuned for the exact date!

Where? TBA, Previously at the Chateau Laurier

Tickets are usually $50 for dinner and the dance or just $20 for only the dance but exact prices are TBD.

See here for 2015's Pictures! (https://www.facebook.com/media/set/?set=a.1013917245291146.1073741832.977321305617407&type=1)"

Please somehow make the link the word "here" for people to click on.

Please have this done by the end of the month (June).

--Aiden
