### ISSUE TITLE
New docs to add

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#97]
[By-Law 1 - Elections.pdf](https://github.com/abejfehr/CSSS/files/870291/By-Law.1.-.Elections.pdf)
[CSSS Constitution (Mar 2017).pdf](https://github.com/abejfehr/CSSS/files/870292/CSSS.Constitution.Mar.2017.pdf)

These are to replace the docs currently on the website

[27 Feb 2017 Mintues.docx](https://github.com/abejfehr/CSSS/files/870293/27.Feb.2017.Mintues.docx)

Minutes from the last meeting to add

**Comment by abejfehr** [comment]
Added
